version: '3.7'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: testlearn
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  app:
    depends_on:
      - mongo
    container_name: backend
    build: .
    ports:
      - 5000:5000
    command: node index.js
    environment:
      DB_URI: mongodb://root:rootpassword@mongo:27017/testlearn
      DEBUG: express:*

volumes:
  mongodb_data_container:


